/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
    public static void main(String[] args) {
        LinkedList newList = new LinkedList();

        newList.insert(5);
        newList.insert(4);
        newList.insert(3);
        newList.insert(2);
        newList.insert(1);
        newList.insert(0);
        newList.insert("ABD");
        newList.insert("Hello");
        newList.append(11);
        newList.append(12);
 //        newList.append(13);
 //        newList.append(9);
        newList.insertBefore(3,"im the value befor 3");
        newList.insertAfter(0,"im the value after 0");

        System.out.println(newList.toString());
        System.out.println(newList.includes(9));
        System.out.println(newList.includes(3));
        System.out.println(newList.includes("Hello"));
        System.out.println(newList.includes("im the value after 0"));

        // code callenge 07
        System.out.println(newList.kthFromEnd(2));//output 5
        System.out.println(newList.kthFromEnd(0));//output 12

        // code callenge 08
        LinkedList newList2 = new LinkedList();

        newList2.insert(5);
        newList2.insert(4);
        newList2.insert(3);
        newList2.insert(2);
        newList2.insert(1);

        System.out.println(newList);
        System.out.println(newList2);
        System.out.println( LinkedList.zipLists(newList,newList2));
        }
    }


