/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
    public static void main(String[] args) {
        LinkedList newList = new LinkedList();

        newList.insert(5);
        newList.insert(4);
        newList.insert(3);
        newList.insert(2);
        newList.insert(1);
        newList.insert(0);
        newList.insert("ABD");
        newList.insert("Hello");


        System.out.println(newList.toString());
        System.out.println(newList.includes(9));
        System.out.println(newList.includes(3));
        System.out.println(newList.includes("Hello"));
        }
    }


