/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;
import stackAndQueue.AnimalShelterPackage.Cat;
import stackAndQueue.AnimalShelterPackage.Dog;
import java.util.Locale;
import static stackAndQueue.MultiBracketValidation.validateBrackets;

public class Library {
    public static void main(String[] args) {
//        Stack<Integer> myStack = new Stack<Integer>();
//
//        myStack.push(3);
//        myStack.push(5);
//        myStack.push(2);
//        myStack.push(1);
//
//     System.out.println(myStack);
//
//
//        Queue<Integer> myQueue = new Queue<>();
//        myQueue.enqueue(10);
//        myQueue.enqueue(9);
//        myQueue.enqueue(5);
//        myQueue.enqueue(6);
//        myQueue.enqueue(3);
//        myQueue.enqueue(1);
//
//        System.out.println(myQueue.toString());
//
//        System.out.println();
//        System.out.println(myQueue.peek());
//        System.out.println(myQueue.peek());
//        System.out.println(myQueue.dequeue());
//        System.out.println(myQueue.dequeue());
//        System.out.println(myQueue.peek());
//
//
//
//        System.out.println(myQueue.size);
//
//
//        PseudoQueue<Integer> pQueue = new PseudoQueue<>();
//        pQueue.enqueue(20);
//        pQueue.enqueue(15);
//        pQueue.enqueue(10);
//        System.out.println(pQueue.getSize());
//        System.out.println(pQueue);
//        System.out.println(pQueue.dequeue());
//        System.out.println(pQueue);

//        AnimalShelter animals = new AnimalShelter();
//
//        Dog d1 = new Dog("dog1");
//        Dog d2 = new Dog("dog2");
//        Dog d3 = new Dog("dog3");
//        Cat c1 = new Cat("cat1");
//        Cat c2 = new Cat("cat2");
//        Cat c3 = new Cat("cat3");
//        animals.enqueue(d1);
//        animals.enqueue(d2);
//        animals.enqueue(c1);
//        animals.enqueue(c2);
//        animals.enqueue(d3);
//        animals.enqueue(c3);
//        System.out.println(animals.getSize());
//        System.out.println(animals.dequeue("cat"));
//        System.out.println(animals.dequeue("dog"));

        System.out.println(validateBrackets("{"));
        System.out.println(validateBrackets("{ }"));
        System.out.println(validateBrackets("{( )}"));
        System.out.println(validateBrackets("{( )}[] ("));
        System.out.println(validateBrackets(""));

    }

}
