/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash.table;
import treeIntersection.TreeIntersection;
import trees.BinaryTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Hashtable<Integer> ids = new Hashtable();

        ids.add("Mohamad",11);
        ids.add("Mohamad2",11);
        ids.add("Yaser",22);
        ids.add("cdd",33);
        ids.add("abc",44);
        System.out.println(ids.toString());
        System.out.println(ids.get("Mohammad"));
        System.out.println(ids.get("Mohamad"));
        System.out.println(ids.get("Mohamad2"));
        System.out.println(ids.get("Yaser"));



        BinaryTree<Integer> tree1 = new BinaryTree();
        BinaryTree<Integer> tree2 = new BinaryTree();
        TreeIntersection treeIntersection = new TreeIntersection();

        tree1.add(3);
        tree1.add(5);
        tree1.add(7);
        tree1.add(2);
        tree1.add(9);
        tree1.add(6);
        tree1.add(4);
        tree1.add(1);


        tree2.add(3);
        tree2.add(5);
        tree2.add(7);
        tree2.add(2);
        tree2.add(9);
        tree2.add(6);
        tree2.add(4);
        tree2.add(1);
        tree2.add(11);



        System.out.println(treeIntersection.findCommonValuesInTwoBinaryTrees(tree1,tree2));


    }
}
