/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash.table;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Hashtable<Integer> ids = new Hashtable();

        ids.add("Mohamad",11);
        ids.add("Yaser",22);
        ids.add("cdd",33);
        ids.add("abc",44);
        System.out.println(ids.toString());
        System.out.println(ids.get("Mohammad"));
        System.out.println(ids.get("Mohamad"));
        System.out.println(ids.get("Yaser"));

    }

}
