/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package margeSort;

import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
        int[] arr = {8,4,23,42,16,15};
        arr = MargeSort.mergeSort(arr);

        System.out.println(Arrays.toString(arr));
    }
}
